name: Windows Build with Boost

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg
          ./vcpkg/bootstrap-vcpkg.bat
          echo "VCPKG_ROOT=$env:GITHUB_WORKSPACE\vcpkg" >> $env:GITHUB_ENV

      - name: Install Boost
        run: ./vcpkg/vcpkg install boost-filesystem:x64-windows boost-system:x64-windows boost-beast:x64-windows boost-dll:x64-windows boost-graph:x64-windows boost-asio:x64-windows

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake .. -G "Visual Studio 17 2022" -A x64 -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake"

      - name: Build
        run: |
          cd build
          cmake --build . --config Release

      # 4. 上传 ZIP 文件
      - name: Upload Artifact Zip
        uses: actions/upload-artifact@v4
        with:
          name: ServerEXE
          path: |
            D:\a\mahjong-cpp\mahjong-cpp\build\src\server\Release\nanikiru.exe
            D:\a\mahjong-cpp\mahjong-cpp\build\src\src\misc\Release\*.exe
