name: Build Boost Libraries

on:
  workflow_dispatch:  # 允许手动触发
  push:
    branches: [ main ]  # 可根据需要调整触发条件

jobs:
  build-boost:
    runs-on: windows-latest  # 使用 Windows 环境

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Visual Studio 2022 (with MSVC)
      uses: microsoft/setup-msbuild@v1
      with:
        vs-version: '17.0'  # VS 2022

    - name: Download Boost
      run: |
        # 下载 Boost 1.88（替换为你的版本）
        $boostVersion = "1.88.0"
        $boostUrl = "https://boostorg.jfrog.io/artifactory/main/release/$boostVersion/source/boost_$($boostVersion.Replace('.','_')).zip"
        Invoke-WebRequest -Uri $boostUrl -OutFile boost.zip
        Expand-Archive -Path boost.zip -DestinationPath .
        Rename-Item "boost_$($boostVersion.Replace('.','_'))" boost

    - name: Build Boost (动态库)
      run: |
        cd boost
        .\bootstrap.bat
        .\b2 toolset=msvc-14.3 architecture=x64 address-model=64 --with-filesystem --with-system variant=release link=shared

    - name: Upload Boost DLLs as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: boost-dlls
        path: boost/stage/lib/*.dll  # 上传所有生成的 DLL
